apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: concept-candidates-claim0
  name: concept-candidates-claim0
spec:
  storageClassName: ibmc-file-gold
  accessModes:
  - ReadOnlyMany
  resources:
    requests:
      storage: 100Mi
status: {}
